# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.9

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: run tests
          command: /bin/sh go.sh test

workflows:
  build_test_deploy:
    jobs:
      - build_test