# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.9

    steps:
      - checkout
      - run:
          name: install dependencies
          command: /bin/sh go.sh install
      - run:
          name: run tests
          command: /bin/sh go.sh test
  build_and_push_image:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image and push to gcr
          command: /bin/sh go.sh build_and_push

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - build_and_push_image:
          requires:
            - build_test
